use_frameworks!

platform :ios, '9.0'

target 'YLBFramework_Example' do
#  pod 'YLBFramework', :path => '../'
pod 'YLBFramework', :path => '../YLBFramework-0.1.3'

  target 'YLBFramework_Tests' do
    inherit! :search_paths

    
  end
end
